# Generated by Django 5.0.4 on 2024-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
